name: rlvc
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.15.0=pyhd3eb1b0_0
  - astor=0.8.1=py36h06a4308_0
  - blas=1.0=mkl
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.3.29=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - coverage=5.5=py36h27cfd23_2
  - cudatoolkit=9.2=0
  - cudnn=7.6.5=cuda9.2_0
  - cupti=9.2.148=0
  - cython=0.29.24=py36h295c915_0
  - dataclasses=0.8=pyh4f3eec9_6
  - gast=0.5.3=pyhd3eb1b0_0
  - grpcio=1.36.1=py36h2157cd5_1
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - importlib-metadata=4.8.1=py36h06a4308_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - markdown=3.3.4=py36h06a4308_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.3=h7f8727e_2
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - protobuf=3.17.2=py36h295c915_0
  - python=3.6.13=h12debd9_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py36h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=hc218d9a_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he74679b_0
  - tensorflow-base=1.12.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36h06a4308_1
  - tk=8.6.11=h1ccaba5_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - imageio==2.15.0
    - pillow==8.4.0
    - scipy==1.2.0
prefix: /home/sigaida/miniconda3/envs/rlvc
